# -*- coding: utf-8 -*-
"""Laboratori3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qmeK-g3hgZzhrMwok18T0HTF_wvAzfFa
"""

! wget https://raw.githubusercontent.com/lourrdesmoreno/casas/main/Datoslimpio.csv

import pandas as pd
data = pd.read_csv("Datoslimpio.csv")
data

#data.info()

! wget https://raw.githubusercontent.com/lourrdesmoreno/casas/main/salario2.csv

import pandas as pd
import numpy as np

data2 = pd.read_csv("salario2.csv")
data2

#print(data2['salarios '] )

from random import choice
descuento = (data2['salarios '] * 0.4)
#print (descuento)
u_aleatorio = choice(descuento)

ICN = 0.055/12
ICV = 0.015/12

precioVenta= data['precio de Venta']
#print (precioVenta)

len(data['vivienda nueva /vivienda de segunta'])
import math
import numpy as np
vec = []
for pos, estado in enumerate(data['vivienda nueva /vivienda de segunta']):
 
  if estado == 2.0:
    de = (ICV * precioVenta[pos])
    nu1 = 1+ICV
    nu = (1 - math.pow((nu1),-360)) 
    p = round(de/nu)
    vec.append(p)
   # vec=np.array(p)
    #print("Valor 2.0 ==> {}".format(p))
  else:
    de = (ICN * precioVenta[pos])
    nu1 = 1+ICN
    nu = 1 - math.pow((nu1),-360)  
    p1 = round(de/nu)
    vec.append(p1)
   # vec=np.array(p1)
    #print("valor 1.0 ==> {}".format(p1))

print('Usuario seleccionado: ')
print(u_aleatorio)

df=pd.DataFrame(data)
comparacion = []
for i in range(374):
 if vec[i] <= u_aleatorio:
   print(df.iloc[i])
   print('')
   comparacion.append(vec[i])

import csv
ruta = 'Datoslimpio.csv'
with open(ruta, newline='',encoding='utf-8') as f:
  c = csv.DictReader(f)
  for r in c:
    print(r['Nombre'])

len(comparacion)

comparacion